# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='College Name')),
                ('details', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Course Name')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('max_years', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], help_text='Maximum duration this course offers.', max_length=1, verbose_name='Years')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='courses',
            field=models.ManyToManyField(related_name='colleges', to='college.Course'),
        ),
    ]
